### PR TITLE
Add javascript module template

### PR DESCRIPTION
**Pull request by bierik**
Depends on https://github.com/4teamwork/ftw-buildouts/pull/52

### CODE REVIEW

**Comment by jone** [comment]
It seems you have based your template on the `module` template, which meanwhile was updated.
You therefore need to re-apply the changes on the `module` template to your template.
- [x] Please verify each commit on master since you've copied the template.

**Comment by bierik** [comment]
@jone updated

**Comment by jone** [comment]
@bierik It would be great if you could update the README template of the module so that it contains the important infos, such as how to build javascript or how to run the javascript tests.

**Comment by bierik** [comment]
@jone updated

**Comment by jone** [comment]
@elioschmutz do you want to take a look too?

**Review by jone — APPROVED** [review]

**Review by elioschmutz — CHANGES_REQUESTED** [review]
@bierik as discussed:
- generated js-file shuld be named like first.second.js (i.e. example.javascript.js) instead of second.js to prevent naming conflicts. Additionally, its easier to find modules if you can access it with namespaces.

**Comment by bierik** [comment]
@elioschmutz updated
@raphael-s could you please try to follow the instructions on https://devdocs.4teamwork.ch/entwicklungsumgebung/javascript/ to setup your javascript environment and the try to generate a javascript module with this new bobtemplate

**Review by elioschmutz — APPROVED** [review]

**Pull request merged**
