### PR TITLE
Move plone.app.contenttypes-permissions to ftw.lawgiver where they belongs to

### LINKED ISSUE #22: Move p.a.contenttypes lawgiver configuration to lawgiver
ftw.lawgiver's [lawgiver.zcml](https://github.com/4teamwork/ftw.lawgiver/blob/master/ftw/lawgiver/lawgiver.zcml) contains the permission mappings for standard Plone.
Since plone.app.contenttypes is standard Plone we should move the p.a.contenttypes mapping from [our lawgiver.zcml](https://github.com/4teamwork/ftw.bob.web/blob/master/ftw/bob/web/template/+package.fullname+/+package.part_1+/+package.part_2+/lawgiver.zcml#L7-L17) to the `lawgiver.zcml` of `ftw.lawgiver`.

### PR DESCRIPTION
**Pull request by elioschmutz**
Move plone.app.contenttypes-permissions to ftw.lawgiver where they belongs to.

Closes #22

### CODE REVIEW

**Comment by mbaechtold** [comment]
4teamwork/ftw.lawgiver#67 has been merged in the meantime so you could continue on this one...

**Comment by elioschmutz** [comment]
@mbaechtold 👍

**Comment by mbaechtold** [comment]
What about a new release of `ftw.lawgiver` so we don't need to install it from source?

**Comment by elioschmutz** [comment]
👍 

I also removed the recently released `ftw.theming` and `plonetheme.blueberry` from source.

there are now two packages left: `ftw.mobile` and `ftw.workspace`. This packages are not ready to release yet.

**Pull request merged**
