### PR TITLE
Fix absolute path in pot file to relative

### LINKED ISSUE #151: Fix pot file in intranet template
There's a hardcoded path segment (copied from another project), see https://github.com/4teamwork/bobtemplates.4teamwork/blob/e256d9077be4ed3870bbab7fc9dd34befd173f62/bobtemplates/intranet/%2Bpackage.fullname%2B/%2Bpackage.part_1%2B/%2Bpackage.part_2%2B/locales/%2Bpackage.fullname%2B-manual.pot.bob#L17

This should be replaced with a variable for mr.bob.

### PR DESCRIPTION
**Pull request by busykoala**
Fix #151

### CODE REVIEW

**Review by mbaechtold — APPROVED** [review]
Nice 👍 Feel free to merge this pull request once the tests have passed.

**Comment by busykoala** [comment]
I don't understand the failed test message or rather how to fix it. I guess I have to add the `+` lines to the `definition.xml` files. But since I can't find the context by neighbouring lines I'm a bit lost where to put them.

**Comment by mbaechtold** [comment]
This is not your fault. I have fixed this in https://github.com/4teamwork/bobtemplates.4teamwork/pull/153. As soon as that pull request has been merged, you can rebase your feature branch onto the `master`-Branch.

**Comment by mbaechtold** [comment]
#153 has been merged. Please rebase onto the `master` branch now.

**Comment by busykoala** [comment]
👍

**Review by mbaechtold — APPROVED** [review]
Nice 👍 Thank you very much!

**Pull request merged**
